# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9842aad13247cd379e6cf830dc99d8bdebf79a5ab6f4ec48f80e79e2ef0b204de402eb14aeb4fffe4925b85c37bd8502e582592003ece5c7e3fde3298f06287a

test:
  secret_key_base: 38f1eba39d5be14e3f0cc5ce39b36f72a230bafe0adb6bc8f76d924302a34b5dd3e832d0901c7adfd3ebf9f846efbb753d1e5acae75a193eb15a226be828cbca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
